# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/titan/Documents/MealManagementSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/titan/Documents/MealManagementSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/titan/Documents/MealManagementSystem/CMakeFiles /home/titan/Documents/MealManagementSystem//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/titan/Documents/MealManagementSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MealManagementSystem

# Build rule for target.
MealManagementSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MealManagementSystem
.PHONY : MealManagementSystem

# fast build rule for target.
MealManagementSystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/build
.PHONY : MealManagementSystem/fast

#=============================================================================
# Target rules for targets named MealManagementSystem_autogen_timestamp_deps

# Build rule for target.
MealManagementSystem_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MealManagementSystem_autogen_timestamp_deps
.PHONY : MealManagementSystem_autogen_timestamp_deps

# fast build rule for target.
MealManagementSystem_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem_autogen_timestamp_deps.dir/build.make CMakeFiles/MealManagementSystem_autogen_timestamp_deps.dir/build
.PHONY : MealManagementSystem_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MealManagementSystem_autogen

# Build rule for target.
MealManagementSystem_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MealManagementSystem_autogen
.PHONY : MealManagementSystem_autogen

# fast build rule for target.
MealManagementSystem_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem_autogen.dir/build.make CMakeFiles/MealManagementSystem_autogen.dir/build
.PHONY : MealManagementSystem_autogen/fast

MealManagementSystem_autogen/mocs_compilation.o: MealManagementSystem_autogen/mocs_compilation.cpp.o
.PHONY : MealManagementSystem_autogen/mocs_compilation.o

# target to build an object file
MealManagementSystem_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/MealManagementSystem_autogen/mocs_compilation.cpp.o
.PHONY : MealManagementSystem_autogen/mocs_compilation.cpp.o

MealManagementSystem_autogen/mocs_compilation.i: MealManagementSystem_autogen/mocs_compilation.cpp.i
.PHONY : MealManagementSystem_autogen/mocs_compilation.i

# target to preprocess a source file
MealManagementSystem_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/MealManagementSystem_autogen/mocs_compilation.cpp.i
.PHONY : MealManagementSystem_autogen/mocs_compilation.cpp.i

MealManagementSystem_autogen/mocs_compilation.s: MealManagementSystem_autogen/mocs_compilation.cpp.s
.PHONY : MealManagementSystem_autogen/mocs_compilation.s

# target to generate assembly for a file
MealManagementSystem_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/MealManagementSystem_autogen/mocs_compilation.cpp.s
.PHONY : MealManagementSystem_autogen/mocs_compilation.cpp.s

src/attendance.o: src/attendance.cpp.o
.PHONY : src/attendance.o

# target to build an object file
src/attendance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/attendance.cpp.o
.PHONY : src/attendance.cpp.o

src/attendance.i: src/attendance.cpp.i
.PHONY : src/attendance.i

# target to preprocess a source file
src/attendance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/attendance.cpp.i
.PHONY : src/attendance.cpp.i

src/attendance.s: src/attendance.cpp.s
.PHONY : src/attendance.s

# target to generate assembly for a file
src/attendance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/attendance.cpp.s
.PHONY : src/attendance.cpp.s

src/dailymenupage.o: src/dailymenupage.cpp.o
.PHONY : src/dailymenupage.o

# target to build an object file
src/dailymenupage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/dailymenupage.cpp.o
.PHONY : src/dailymenupage.cpp.o

src/dailymenupage.i: src/dailymenupage.cpp.i
.PHONY : src/dailymenupage.i

# target to preprocess a source file
src/dailymenupage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/dailymenupage.cpp.i
.PHONY : src/dailymenupage.cpp.i

src/dailymenupage.s: src/dailymenupage.cpp.s
.PHONY : src/dailymenupage.s

# target to generate assembly for a file
src/dailymenupage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/dailymenupage.cpp.s
.PHONY : src/dailymenupage.cpp.s

src/database.o: src/database.cpp.o
.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

src/expense.o: src/expense.cpp.o
.PHONY : src/expense.o

# target to build an object file
src/expense.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/expense.cpp.o
.PHONY : src/expense.cpp.o

src/expense.i: src/expense.cpp.i
.PHONY : src/expense.i

# target to preprocess a source file
src/expense.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/expense.cpp.i
.PHONY : src/expense.cpp.i

src/expense.s: src/expense.cpp.s
.PHONY : src/expense.s

# target to generate assembly for a file
src/expense.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/expense.cpp.s
.PHONY : src/expense.cpp.s

src/expensetrackingpage.o: src/expensetrackingpage.cpp.o
.PHONY : src/expensetrackingpage.o

# target to build an object file
src/expensetrackingpage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/expensetrackingpage.cpp.o
.PHONY : src/expensetrackingpage.cpp.o

src/expensetrackingpage.i: src/expensetrackingpage.cpp.i
.PHONY : src/expensetrackingpage.i

# target to preprocess a source file
src/expensetrackingpage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/expensetrackingpage.cpp.i
.PHONY : src/expensetrackingpage.cpp.i

src/expensetrackingpage.s: src/expensetrackingpage.cpp.s
.PHONY : src/expensetrackingpage.s

# target to generate assembly for a file
src/expensetrackingpage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/expensetrackingpage.cpp.s
.PHONY : src/expensetrackingpage.cpp.s

src/finance.o: src/finance.cpp.o
.PHONY : src/finance.o

# target to build an object file
src/finance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/finance.cpp.o
.PHONY : src/finance.cpp.o

src/finance.i: src/finance.cpp.i
.PHONY : src/finance.i

# target to preprocess a source file
src/finance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/finance.cpp.i
.PHONY : src/finance.cpp.i

src/finance.s: src/finance.cpp.s
.PHONY : src/finance.s

# target to generate assembly for a file
src/finance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/finance.cpp.s
.PHONY : src/finance.cpp.s

src/financialoverviewpage.o: src/financialoverviewpage.cpp.o
.PHONY : src/financialoverviewpage.o

# target to build an object file
src/financialoverviewpage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/financialoverviewpage.cpp.o
.PHONY : src/financialoverviewpage.cpp.o

src/financialoverviewpage.i: src/financialoverviewpage.cpp.i
.PHONY : src/financialoverviewpage.i

# target to preprocess a source file
src/financialoverviewpage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/financialoverviewpage.cpp.i
.PHONY : src/financialoverviewpage.cpp.i

src/financialoverviewpage.s: src/financialoverviewpage.cpp.s
.PHONY : src/financialoverviewpage.s

# target to generate assembly for a file
src/financialoverviewpage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/financialoverviewpage.cpp.s
.PHONY : src/financialoverviewpage.cpp.s

src/loginwindow.o: src/loginwindow.cpp.o
.PHONY : src/loginwindow.o

# target to build an object file
src/loginwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/loginwindow.cpp.o
.PHONY : src/loginwindow.cpp.o

src/loginwindow.i: src/loginwindow.cpp.i
.PHONY : src/loginwindow.i

# target to preprocess a source file
src/loginwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/loginwindow.cpp.i
.PHONY : src/loginwindow.cpp.i

src/loginwindow.s: src/loginwindow.cpp.s
.PHONY : src/loginwindow.s

# target to generate assembly for a file
src/loginwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/loginwindow.cpp.s
.PHONY : src/loginwindow.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/mealattendancepage.o: src/mealattendancepage.cpp.o
.PHONY : src/mealattendancepage.o

# target to build an object file
src/mealattendancepage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/mealattendancepage.cpp.o
.PHONY : src/mealattendancepage.cpp.o

src/mealattendancepage.i: src/mealattendancepage.cpp.i
.PHONY : src/mealattendancepage.i

# target to preprocess a source file
src/mealattendancepage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/mealattendancepage.cpp.i
.PHONY : src/mealattendancepage.cpp.i

src/mealattendancepage.s: src/mealattendancepage.cpp.s
.PHONY : src/mealattendancepage.s

# target to generate assembly for a file
src/mealattendancepage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/mealattendancepage.cpp.s
.PHONY : src/mealattendancepage.cpp.s

src/menu.o: src/menu.cpp.o
.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/menuhistorypage.o: src/menuhistorypage.cpp.o
.PHONY : src/menuhistorypage.o

# target to build an object file
src/menuhistorypage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menuhistorypage.cpp.o
.PHONY : src/menuhistorypage.cpp.o

src/menuhistorypage.i: src/menuhistorypage.cpp.i
.PHONY : src/menuhistorypage.i

# target to preprocess a source file
src/menuhistorypage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menuhistorypage.cpp.i
.PHONY : src/menuhistorypage.cpp.i

src/menuhistorypage.s: src/menuhistorypage.cpp.s
.PHONY : src/menuhistorypage.s

# target to generate assembly for a file
src/menuhistorypage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menuhistorypage.cpp.s
.PHONY : src/menuhistorypage.cpp.s

src/menumanagementpage.o: src/menumanagementpage.cpp.o
.PHONY : src/menumanagementpage.o

# target to build an object file
src/menumanagementpage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menumanagementpage.cpp.o
.PHONY : src/menumanagementpage.cpp.o

src/menumanagementpage.i: src/menumanagementpage.cpp.i
.PHONY : src/menumanagementpage.i

# target to preprocess a source file
src/menumanagementpage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menumanagementpage.cpp.i
.PHONY : src/menumanagementpage.cpp.i

src/menumanagementpage.s: src/menumanagementpage.cpp.s
.PHONY : src/menumanagementpage.s

# target to generate assembly for a file
src/menumanagementpage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/menumanagementpage.cpp.s
.PHONY : src/menumanagementpage.cpp.s

src/period.o: src/period.cpp.o
.PHONY : src/period.o

# target to build an object file
src/period.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/period.cpp.o
.PHONY : src/period.cpp.o

src/period.i: src/period.cpp.i
.PHONY : src/period.i

# target to preprocess a source file
src/period.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/period.cpp.i
.PHONY : src/period.cpp.i

src/period.s: src/period.cpp.s
.PHONY : src/period.s

# target to generate assembly for a file
src/period.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/period.cpp.s
.PHONY : src/period.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/user.o: src/user.cpp.o
.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i
.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s
.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

src/usermanagementpage.o: src/usermanagementpage.cpp.o
.PHONY : src/usermanagementpage.o

# target to build an object file
src/usermanagementpage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/usermanagementpage.cpp.o
.PHONY : src/usermanagementpage.cpp.o

src/usermanagementpage.i: src/usermanagementpage.cpp.i
.PHONY : src/usermanagementpage.i

# target to preprocess a source file
src/usermanagementpage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/usermanagementpage.cpp.i
.PHONY : src/usermanagementpage.cpp.i

src/usermanagementpage.s: src/usermanagementpage.cpp.s
.PHONY : src/usermanagementpage.s

# target to generate assembly for a file
src/usermanagementpage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/usermanagementpage.cpp.s
.PHONY : src/usermanagementpage.cpp.s

src/userprofilepage.o: src/userprofilepage.cpp.o
.PHONY : src/userprofilepage.o

# target to build an object file
src/userprofilepage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/userprofilepage.cpp.o
.PHONY : src/userprofilepage.cpp.o

src/userprofilepage.i: src/userprofilepage.cpp.i
.PHONY : src/userprofilepage.i

# target to preprocess a source file
src/userprofilepage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/userprofilepage.cpp.i
.PHONY : src/userprofilepage.cpp.i

src/userprofilepage.s: src/userprofilepage.cpp.s
.PHONY : src/userprofilepage.s

# target to generate assembly for a file
src/userprofilepage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MealManagementSystem.dir/build.make CMakeFiles/MealManagementSystem.dir/src/userprofilepage.cpp.s
.PHONY : src/userprofilepage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MealManagementSystem_autogen"
	@echo "... MealManagementSystem_autogen_timestamp_deps"
	@echo "... MealManagementSystem"
	@echo "... MealManagementSystem_autogen/mocs_compilation.o"
	@echo "... MealManagementSystem_autogen/mocs_compilation.i"
	@echo "... MealManagementSystem_autogen/mocs_compilation.s"
	@echo "... src/attendance.o"
	@echo "... src/attendance.i"
	@echo "... src/attendance.s"
	@echo "... src/dailymenupage.o"
	@echo "... src/dailymenupage.i"
	@echo "... src/dailymenupage.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/expense.o"
	@echo "... src/expense.i"
	@echo "... src/expense.s"
	@echo "... src/expensetrackingpage.o"
	@echo "... src/expensetrackingpage.i"
	@echo "... src/expensetrackingpage.s"
	@echo "... src/finance.o"
	@echo "... src/finance.i"
	@echo "... src/finance.s"
	@echo "... src/financialoverviewpage.o"
	@echo "... src/financialoverviewpage.i"
	@echo "... src/financialoverviewpage.s"
	@echo "... src/loginwindow.o"
	@echo "... src/loginwindow.i"
	@echo "... src/loginwindow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/mealattendancepage.o"
	@echo "... src/mealattendancepage.i"
	@echo "... src/mealattendancepage.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/menuhistorypage.o"
	@echo "... src/menuhistorypage.i"
	@echo "... src/menuhistorypage.s"
	@echo "... src/menumanagementpage.o"
	@echo "... src/menumanagementpage.i"
	@echo "... src/menumanagementpage.s"
	@echo "... src/period.o"
	@echo "... src/period.i"
	@echo "... src/period.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
	@echo "... src/usermanagementpage.o"
	@echo "... src/usermanagementpage.i"
	@echo "... src/usermanagementpage.s"
	@echo "... src/userprofilepage.o"
	@echo "... src/userprofilepage.i"
	@echo "... src/userprofilepage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

